- src/mkdocstrings_handlers/python/handler.py
Issue mkdocstrings/mkdocstrings#311
Requires https://github.com/mkdocstrings/mkdocstrings/pull/425
> feat: Add paths option

- mkdocs.yml
- src/mkdocstrings_handlers/python/handler.py
This change allows for values in the paths configuration option to be
globs by resolving them before passing them off to griffe.
fixes #33
> feat: Add support for globs in paths configuration

- docs/gen_ref_nav.py
We need to provide a relative path to go up out of the docs dir.
See
https://github.com/mkdocstrings/mkdocstrings/pull/443
> Fix edit page link to python files for reference pages

- src/mkdocstrings_handlers/python/handler.py
- tests/test_handler.py
fix #42 
based on the documentation: "Non-absolute paths are computed as relative to MkDocs configuration file."
> fix: globs in path if cwd is not the cfg file loc

- src/mkdocstrings_handlers/python/handler.py
- tests/test_handler.py
Using `os.chdir` to switch to the directory containing the config file (introduced in #43) fails if `config_file_path` only contains a filename but no directories (similar to timvink/mkdocs-table-reader-plugin#16). Replacing an empty result of `os.dirname` should avoid this.
> fix: ensure dirname(config_file_path) is not empty

- pyproject.toml
- src/mkdocstrings_handlers/python/handler.py
Fixes problems reported by mypy.
Related: https://github.com/python/typeshed/issues/8430
> fix: Fix types

- docs/schema.json
- pyproject.toml
- src/mkdocstrings_handlers/python/handler.py
Related: https://github.com/mkdocstrings/mkdocstrings/issues/510
Depends-On: https://github.com/mkdocstrings/mkdocstrings/pull/511
> Allow custom list of domains for inventories

- docs/schema.json
- src/mkdocstrings_handlers/python/handler.py
- src/mkdocstrings_handlers/python/templates/material/_base/docstring.html
- src/mkdocstrings_handlers/python/templates/material/_base/function.html
Related to mkdocstrings/mkdocstrings#466.
List of new options (view docstring in git diff for more details):
- `show_docstring_description`
- `show_docstring_attributes`
- `show_docstring_parameters`
- `show_docstring_other_parameters`
- `show_docstring_raises`
- `show_docstring_warns`
- `show_docstring_yields`
- `show_docstring_receives`
- `show_docstring_returns`
- `show_docstring_examples`
In total, **10** new options, covering all the docstring types.
**Details:**
- My approach was to start with the sections mentioned inside `material/_base/docstring.html`, but combined `section.kind=="admonition"` and `section.kind=="text"` under the same `show_docstring_description` option. Just felt strange to separate them as I can't imagine a scenario I want one but not the other, but let me know …
> feat: add new show options for docstrings

- docs/schema.json
- src/mkdocstrings_handlers/python/handler.py
Hi
I would like to suggest adding an option (false by default) to set griffe's resolve external modules flag to true.
What are your thoughts about it? Did I do it correctly? As I am not a native English speaker, my documentation my need some improvement.
> feat: Allow resolving alias to external modules

- docs/schema.json
- docs/usage.md
- src/mkdocstrings_handlers/python/handler.py
This PR extends #60 to allow loading any external module
> feat: Allow resolving alias to any external module

- src/mkdocstrings_handlers/python/rendering.py
Lowering this to info level avoids this causing strict MkDocs builds to fail
> refactor: Switch to an info level log for when black's not installed

- docs/usage/extensions.md
- mkdocs.yml
- src/mkdocstrings_handlers/python/handler.py
- src/mkdocstrings_handlers/python/rendering.py
- src/mkdocstrings_handlers/python/templates/material/_base/children.html
Depends on https://github.com/mkdocstrings/mkdocstrings/pull/569
> feat: Support custom templates through objects' `template` attribute

- src/mkdocstrings_handlers/python/templates/material/_base/labels.html
These labels are `set`s which have no defined order. Define *some* order, so they don't flip-flop depending on the environment.
https://github.com/mkdocs/regressions/actions/runs/5212332561/jobs/9405787375
> Show labels in deterministic order

- src/mkdocstrings_handlers/python/handler.py
- tests/test_handler.py
There were a few different ways to accomplish this.
1. Modify griffe to have it accept a base_path (which defaults to CWD) and resolve paths relative to it.
2. Modify mkdocsstrings-python to resolve paths so that only absolute paths are passed to griffe.
Ultimately I went with the second option as griffe does not know about (and has no need to know about) mkdocstrings. It seems reasonable to me that griffe should expect to receive already resolved paths. As mkdocstrings-python is the glue between mkdocstrings and griffe, I thought that would be the most logical place to address the issue.
That said, much of the logic to separate the path from the rest of the data in the config options replicates the logic in `griffe.extensions.load_extensions()`. From a code efficiency point-of-view, it …
> Make extension paths relative to config file

- docs/usage/configuration/general.md
- src/mkdocstrings_handlers/python/handler.py
This allows using the feature in griffe that searches for stubs packages
Related: https://github.com/mkdocstrings/griffe/pull/221
> feat: Add option to search for stubs packages

- docs/usage/configuration/members.md
- src/mkdocstrings_handlers/python/handler.py
- src/mkdocstrings_handlers/python/templates/material/_base/labels.html
Fixes #120. I'm not sure if this needs a test?
> Add `show_labels` config option

- docs/usage/configuration/docstrings.md
As per the branch name, it's a super-important fix.
🚀
> Correct `PrintOK` doctest examples

- docs/usage/customization.md
- src/mkdocstrings_handlers/python/handler.py
This link is currently resulting in a 404 - please let me know if this is not the right page to link to. Cheers!
> Fix link to griffe.Parsers in docstrings options summary

- docs/.glossary.md
- docs/schema.json
- docs/usage/configuration/signatures.md
- src/mkdocstrings_handlers/python/handler.py
- src/mkdocstrings_handlers/python/rendering.py
- tests/test_rendering.py
Until https://github.com/astral-sh/ruff/issues/659 is implemented, it could still be helpful to use `ruff` to format the signatures.
Feel free to close the PR if you believe the perf impact is too big when spanning multiple subprocesses.
> Allow ruff to be used as a formatter

- docs/usage/configuration/general.md
- src/mkdocstrings_handlers/python/handler.py
The `force_inspection` argument cannot be configured directly via `mkdocs.yml`. This change introduces a straightforward way to pass the option by forwarding it to the `GriffeLoader`.
- Added `force_inspection` to `PythonHandler.default_config` with a default value of `False`.
- Forwarded the `force_inspection` value to the `GriffeLoader` constructor.
Fixes #94
> feat: allow  `force_inspection` option to be configurable

- src/mkdocstrings_handlers/python/rendering.py
When `summary` is set to True in `mkdocs.yml`, one-line `@property` attributes are shown as they are without the stripping of the annotation. For example `str: xxxxxx` is shown as `str:xxxx` in the `Attributes` section of the summary. This PR strips out any annotations, effectively leaving the `xxxxxxx` part in the summary which is what is desired.
- add helper function in `do_as_attributes_section` to parse the description from the docstring accounting for `@property` style docstrings too.
> feat: remove annotations for properties in attributes section of summary

- docs/usage/index.md
I am currently working to integrate `mkdocstrings` to generate project documentation, and I was a bit confused by the example text that did not match the example code.
> fix example usage of inventories

- src/mkdocstrings_handlers/python/_internal/config.py
- tests/test_handler.py
Correct the handling of the `base_url` in the inventory class and ensure that the inventory URLs are rendered using the specified `base_url`. 
Add a test to verify this functionality.
Fixes https://github.com/mkdocstrings/python/issues/268.
> Fix inventory `base_url` handling

- src/mkdocstrings_handlers/python/templates/material/_base/attribute.html.jinja
- src/mkdocstrings_handlers/python/templates/material/_base/class.html.jinja
- src/mkdocstrings_handlers/python/templates/material/_base/function.html.jinja
- src/mkdocstrings_handlers/python/templates/material/_base/module.html.jinja
- tests/snapshots/__init__.py
- tests/snapshots/external/2eef87791b974c724d2cd98e40bb25994087bc836868f63da18557a6094a00ee.html
- tests/snapshots/external/480324b25439ea41507fdda100045132d578af0e1df1219c08bc9ea0bea1f39c.html
- tests/snapshots/external/51deee0f00f35b0902f82fb96a36d547a80dfbb41a311dabd94b96fd968b83bc.html
- tests/snapshots/external/d1dd339f926026210ea46cc75922a8236f43cade477f95e4ce4c9a60248f0a10.html
- tests/test_end_to_end.py
Issue-767: https://github.com/mkdocstrings/mkdocstrings/issues/767
> fix: Use configured heading even when signature is not separated
